title: 개발자 김준호의 깃헙 페이지
tagline: 개발자 김준호의 기술 블로그
description: 개발자 김준호의 깃헙 페이지입니다.

url: "https://junho85.github.io"
baseurl: ""

author:
  name: 김준호
  email: junho85@gmail.com

timezone: Asia/Seoul
lang: ko-KR

github:
  username: junho85

twitter:
  username: junho85

avatar: /assets/img/avatar.jpg

social:
  name: 김준호
  email: junho85@gmail.com
  links:
    - https://github.com/junho85

theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 10
paginate_path: "/page:num/"

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      tail_includes:
        - related-posts
        - post-nav
        - adsense-tail
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

compress_html:
  ignore:
    envs: development

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json
